### ISSUE TITLE
Payload de test et Documentation de la contribution

### ISSUE THREAD

**Issue by roazagba** [v1p3r75/moov-money-api-php-sdk#1]
Bonjour Fortunatus. Tout d'abord je te félicite pour le travail accompli.
Comment avoir les informations de test (username, mot de passe) du marchand Moov Money car ce n'est pas mentionné dans ta documentation. Je pense que l'API Moov Money n'est pas public comme celle de MTN. 

Donc comment tester et par là me permettra de contribuer au projet ?
Et aussi un guide de la contribution sera la bienvenue.
Il faut qu'on est aussi la documentation de l'API Moov Money pour qu'on puisse ajouter de nouvelles fonctionnalités ou améliorer le code. Car sans cela, ça sera du néant pour nous qui voulons contribuer.
Aussi il faut des **DocBlocks** pour les propriétés (attributs, méthodes) d'une classe, ça permettra aux contributeurs de se retrouver dans le code, d'apporter leur expertise.

J'attends votre retour.
Merci.

**Comment by v1p3r75** [comment]
Bonjour,

Tout d’abord, merci pour tes encouragements et ton intérêt pour le projet !

**1. Informations de Test**
Effectivement, comme tu l'as bien noté, l'API Moov Money n'est pas publique comme celle de MTN. Les informations de test (username, mot de passe) sont fournies directement par Moov Money aux entreprises partenaires, et pour des raisons de confidentialité, je ne peux pas partager les credentials que j'utilise actuellement. Pour obtenir ces informations, je te recommande de contacter directement Moov Money ou de passer par une entreprise partenaire qui pourrait te donner un accès aux environnements de test (mon cas actuel).

**2. Documentation de l'API Moov Money**
Je vais ajouter sous peu un fichier avec la documentation officielle de l'API Moov Money dans le repo pour aider tous les contributeurs à bien comprendre le fonctionnement des différentes fonctionnalités. Si tu en as besoin rapidement, n’hésite pas à me transmettre ton email, et je te l'enverrai directement.

**3. Guide de Contribution**
Je travaille sur un guide pour faciliter les contributions au projet. Ce guide comprendra les étapes pour installer et configurer le projet en local, les conventions de code à suivre, et des instructions pour proposer de nouvelles fonctionnalités ou corriger des bugs. Je le publierai bientôt dans le fichier CONTRIBUTING.md du repo.

**4. DocBlocks et Commentaires**
C'est un excellent point, et tu as raison ! J’ai déjà commencé à ajouter des DocBlocks pour les classes, méthodes et attributs pour rendre le code plus lisible et faciliter la compréhension des fonctionnalités pour tous les contributeurs. Ces ajouts seront disponibles dans les prochaines mises à jour du code.

Je te remercie pour tes suggestions constructives. N’hésite pas si tu as d’autres questions ou suggestions !

À bientôt,

Fortunatus KIDJE

**Comment by roazagba** [comment]
Merci Fortunatus pour ton retour.
C'est noté.
Pour la documentation de l'API Moov Money, tu peux l'envoyer à l'adresse email [ana@roazagba.me](mailto:ana@roazagba.me).
